
task: "mt"
data_dir: "data/finetune/mt"

learning_rate: 1.0e-5
batch_size: 4
gradient_accumulation_steps: 4
num_epochs: 5
lr_scheduler_type: "linear"
warmup_steps: 0

eval_batch_size: 8
max_source_length: 512
max_target_length: 512
num_beams: 5
max_new_tokens: 512

source_prefix: ""
direction: "xh-en"
direction_prefix: "Translate Xhosa to English: "
n_train_pairs: 25000

wandb_project: "cpt-mt-xhen-25k"
work_dir: "/scratch/rmdrak003/finetune_work"
results_dir: "results_mt_xhen_5epoch_25k"
