
# Model Configuration
model_name_or_path: "google-t5/t5-large"
max_seq_length: 512
max_target_length: 512

# Training Configuration
learning_rate: 1.0e-4
per_device_batch_size: 16
gradient_accumulation_steps: 64
total_steps: 10000
warmup_steps: 5000

# Checkpointing Configuration
output_dir: "/scratch/rmdrak003/results/t5/lafand-bilingual"

# Experiment Tracking
wandb_project: "cpt-learning-dynamics"
wandb_run_name: "t5-xho-eng-bilingual"
