
task: "d2t"
data_dir: "data/finetune/d2t"

learning_rate: 1.0e-4
batch_size: 4
num_epochs: 5
lr_scheduler_type: "linear"
warmup_ratio: 0.20

eval_batch_size: 8
max_source_length: 512
max_target_length: 512
num_beams: 5
max_new_tokens: 512
source_prefix: ""

wandb_project: "cpt-bilingual-d2t-1000"
work_dir: "/scratch/rmdrak003/finetune_work"
results_dir: "results_bilingual_d2t_1000"
n_train_examples: 1000
